version: "3.8"

networks:
  default:
    driver: bridge

services:
  fms-api:
    container_name: fms-api
    build: ./fms-api
    restart: unless-stopped
    env_file: ./.env
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
      DATABASE_URI: $DATABASE_URI
    ports:
      - $API_APP_LOCAL_PORT:$API_APP_DOCKER_PORT
      - $API_APP_LOCAL_WEBSOCKET_PORT:$API_APP_LOCAL_WEBSOCKET_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./fms-api:/app
      - /app/node_modules
    networks:
      - default
    depends_on:
      - database

  fms-frontend:
    container_name: fms-frontend
    build:
      context: ./fms-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $FRONTEND_APP_LOCAL_PORT:$FRONTEND_APP_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./fms-frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default

  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    env_file: ./.env
    environment:
      MONOGO_INITDB_DATABASE: $DATABASE_NAME
      MONGO_INITDB_ROOT_USERNAME: $DATABASE_USER
      MONGO_INITDB_ROOT_PASSWORD: $DATABASE_PASS
    volumes:
      - mongo-data:/data/db
    networks:
      - default

volumes:
  mongo-data:
    driver: local
